/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GaleDTRules.DAO.GalePatientDAO;
import GaleDTRules.Classes.*;
import GaleDTRules.DAO.GaleBMIDevDAO;
import GaleDTRules.DAO.GaleDTRulesDAO;
import GaleDTRules.DAO.GaleFloorsDevDAO;
import GaleDTRules.DAO.GaleHRDevDAO;
import GaleDTRules.DAO.GaleSleepDevDAO;
import GaleDTRules.DAO.GaleStepsDevDAO;
import GaleDTRules.DAO.GaleWeightDevDAO;
import GaleDTRules.Tools.DTRulesXML;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.PrintStream;
import java.lang.reflect.Method;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HASEE
 */
public class dtRulesTestingGUI extends javax.swing.JFrame {

    List<Patients> patientList = new LinkedList<>();
    private String RuleSetString = null;
    private String EntryTable = null;
    
    private boolean Compiled = false;
    private boolean Tested = false;
    
    private int TB_Width = 0;
    private boolean TB_Record = false;
    
    /**
     * Creates new form dtRulesTestingGUI
     */
    public dtRulesTestingGUI() {
        initComponents();
        this.setTitle("DTRulesTesting...");
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_UploadDT = new javax.swing.JButton();
        CB_BMI = new javax.swing.JCheckBox();
        CB_Floors = new javax.swing.JCheckBox();
        CB_HR = new javax.swing.JCheckBox();
        CB_Sleep = new javax.swing.JCheckBox();
        CB_Steps = new javax.swing.JCheckBox();
        CB_Weight = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TB_RuleSetName = new javax.swing.JTextField();
        Btn_SelectDT = new javax.swing.JButton();
        Btn_ComplieDT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Select_EntryTable = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        Btn_SelectRuleName = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TA_CompileMsg = new javax.swing.JTextArea();
        TF_SelectedFile = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        INPT_PName = new javax.swing.JTextField();
        Btn_Search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA_PatientInfo = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        Btn_RunSelectedDT = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TA_Results = new javax.swing.JTextArea();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Btn_UploadDT.setText("Upload");
        Btn_UploadDT.setEnabled(false);
        Btn_UploadDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_UploadDTActionPerformed(evt);
            }
        });

        CB_BMI.setText("BMI");
        CB_BMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_BMIActionPerformed(evt);
            }
        });

        CB_Floors.setText("Floors");
        CB_Floors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_FloorsActionPerformed(evt);
            }
        });

        CB_HR.setText("HR");
        CB_HR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_HRActionPerformed(evt);
            }
        });

        CB_Sleep.setText("Sleep");
        CB_Sleep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_SleepActionPerformed(evt);
            }
        });

        CB_Steps.setText("Steps");
        CB_Steps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_StepsActionPerformed(evt);
            }
        });

        CB_Weight.setText("Weight");
        CB_Weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_WeightActionPerformed(evt);
            }
        });

        jLabel3.setText("Select your excel file:");

        jLabel4.setText("Please input or ");

        Btn_SelectDT.setText("...");
        Btn_SelectDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SelectDTActionPerformed(evt);
            }
        });

        Btn_ComplieDT.setText("Compile the DT");
        Btn_ComplieDT.setEnabled(false);
        Btn_ComplieDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ComplieDTActionPerformed(evt);
            }
        });

        jLabel1.setText("Select your entry table:");

        Select_EntryTable.setEnabled(false);

        Btn_SelectRuleName.setText("select");
        Btn_SelectRuleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SelectRuleNameActionPerformed(evt);
            }
        });

        jLabel6.setText("a rule name:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(Select_EntryTable, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_ComplieDT, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_SelectDT, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Btn_SelectRuleName)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addComponent(TB_RuleSetName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Btn_SelectDT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_ComplieDT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Btn_SelectRuleName)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TB_RuleSetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Select_EntryTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        TA_CompileMsg.setColumns(20);
        TA_CompileMsg.setLineWrap(true);
        TA_CompileMsg.setRows(5);
        TA_CompileMsg.setText("The Compile Message will be placed here...\n");
        TA_CompileMsg.setWrapStyleWord(true);
        jScrollPane3.setViewportView(TA_CompileMsg);

        TF_SelectedFile.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TF_SelectedFile))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TF_SelectedFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Patient's Name:");

        Btn_Search.setText("Search");
        Btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INPT_PName)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 189, Short.MAX_VALUE))
                    .addComponent(Btn_Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INPT_PName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_Search)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        TA_PatientInfo.setEditable(false);
        TA_PatientInfo.setColumns(20);
        TA_PatientInfo.setLineWrap(true);
        TA_PatientInfo.setRows(5);
        TA_PatientInfo.setText("The information of the certain Patient will be placed here...\nNow the EDD is fixed..\nAnd the selected decision table should use the data entities defined by the EDD...\n");
        TA_PatientInfo.setWrapStyleWord(true);
        jScrollPane1.setViewportView(TA_PatientInfo);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );

        Btn_RunSelectedDT.setText("Run in the DT");
        Btn_RunSelectedDT.setEnabled(false);
        Btn_RunSelectedDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_RunSelectedDTActionPerformed(evt);
            }
        });

        TA_Results.setEditable(false);
        TA_Results.setColumns(20);
        TA_Results.setLineWrap(true);
        TA_Results.setRows(5);
        TA_Results.setText("The result will be placed here...");
        TA_Results.setWrapStyleWord(true);
        jScrollPane2.setViewportView(TA_Results);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn_RunSelectedDT, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_RunSelectedDT)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(CB_Sleep)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CB_Steps)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CB_Weight)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CB_BMI)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CB_Floors)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CB_HR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Btn_UploadDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CB_Steps)
                    .addComponent(Btn_UploadDT)
                    .addComponent(CB_HR)
                    .addComponent(CB_Floors)
                    .addComponent(CB_BMI)
                    .addComponent(CB_Weight)
                    .addComponent(CB_Sleep))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SearchActionPerformed
        // TODO add your handling code here:
        WriteTA(TA_PatientInfo,"\nGetting Patient info from database...\n"+System.getProperty("user.dir")+"/DTRules/");
        String patientName = INPT_PName.getText();
        GalePatientDAO pdao = new GalePatientDAO();
        Object result = pdao.getTableModel(patientName);
        DefaultTableModel dt = (DefaultTableModel)result;
        int rows = dt.getRowCount();
        int columns = dt.getColumnCount();
        Vector vct = dt.getDataVector();
        WriteTA(TA_PatientInfo,"\nDone.\nData rows:"+rows+"---Data columns:"+columns);
        for(int i = 0; i < rows; i++){//for each row
            Vector data = (Vector)vct.get(i);
            Patients tmp = new Patients();
            Class clazz = tmp.getClass();
            for(int j = 0; j < columns; j++){//for each column
                WriteTA(TA_PatientInfo, "\n"+dt.getColumnName(j)+":"+data.get(j));
                try{
                    Method m = clazz.getMethod("set"+dt.getColumnName(j), Object.class);
                    m.invoke(tmp, data.get(j));
                }catch(Exception e){
                    System.out.println(e.getMessage());
                }
            }
            //Get the all six Dev data from database here
            List<BMI_Dev> bmilist = GetBMIDevFromDB(tmp.getPatientID());
            List<Floors_Dev> floorlist = GetFloorsDevFromDB(tmp.getPatientID());
            List<HR_Dev> hrlist = GetHRDevFromDB(tmp.getPatientID());
            List<Sleep_Dev> sleeplist = GetSleepDevFromDB(tmp.getPatientID());
            List<Steps_Dev> stepslist = GetStepsDevFromDB(tmp.getPatientID());
            List<Weight_Dev> weightlist = GetWeightDevFromDB(tmp.getPatientID());
            tmp.setBMI_Devs(bmilist);
            tmp.setFloors_Devs(floorlist);
            tmp.setHR_Devs(hrlist);
            tmp.setSleep_Devs(sleeplist);
            tmp.setSteps_Devs(stepslist);
            tmp.setWeight_Devs(weightlist);
            patientList.add(tmp);
        }
        SimpleDateFormat bartDateFormat = new SimpleDateFormat("yyyy-MM-dd");
//        for(Patients pt: patientList){
//            WriteTA(TA_Results, "\nname:"+pt.getFullName());
//            WriteTA(TA_Results, "\nage:"+pt.getAge());
//            WriteTA(TA_Results, "\ngender"+pt.getGender());
//            if(pt.getMemberSince() != null)
//                WriteTA(TA_Results, "\nmember since:"+bartDateFormat.format(pt.getMemberSince()));
//        }
//        WriteTA(TA_PatientInfo, "\n\nDONE!");
    }//GEN-LAST:event_Btn_SearchActionPerformed


    private void CheckForUpload() {
        if((CB_BMI.isSelected() || CB_Floors.isSelected() || CB_HR.isSelected()
                || CB_Sleep.isSelected() || CB_Steps.isSelected() || CB_Weight.isSelected())
                && Compiled && Tested)
            Btn_UploadDT.setEnabled(true);
        else
            Btn_UploadDT.setEnabled(false);
    }

    class ExcelFileFilter extends FileFilter {
        public String getDescription() {
            return "*.xls;*.xlsx";
        }
        public boolean accept(File file) {
            String name = file.getName();
            return file.isDirectory() || name.toLowerCase().endsWith(".xls") || name.toLowerCase().endsWith(".xlsx");
        }
    }
    private void Btn_SelectDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SelectDTActionPerformed
        JFileChooser jfc = new JFileChooser();
        ExcelFileFilter eff = new ExcelFileFilter();
        jfc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        jfc.addChoosableFileFilter(eff);
        jfc.setFileFilter(eff);
        int state = jfc.showOpenDialog(null);
        if(state == 1){
            return;
        }else{
            File f = jfc.getSelectedFile();
            TF_SelectedFile.setText(f.getAbsolutePath());
            if(TB_RuleSetName.getText() == null || TB_RuleSetName.getText().equals(""))
                TB_RuleSetName.setText(f.getName().split("[.]")[0]);
            f = null;
            Btn_ComplieDT.setEnabled(true);
        }
    }//GEN-LAST:event_Btn_SelectDTActionPerformed

    private void Btn_ComplieDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ComplieDTActionPerformed
        //add a method that returns the RuleSet string, save it in a temp variable...done
        //check all the directions are exists...done
        //append or create a DTRules.xml with the RuleSet string...done
        //copy the file into certain dir AND COMPILE, then we should take all decision table's name to let user to choose the entry table...done
        //Data we need: BasePath, ConfigFileFileName, RuleSetName, EntryTableName
        //The Edd xls file is fixed for now and maybe it will not be modified or we will not add new entities
        TA_CompileMsg.setText("");
        File dtFile = new File(TF_SelectedFile.getText());
        String ruleName = dtFile.getName().split("[.]")[0];
        DTRulesXML dtrxml = DTRulesXML.getInstance();
        RuleSetString = dtrxml.getRuleSetString();
        WriteTA(TA_CompileMsg, "The RuleSet Generated Info:");
        try{
            dtrxml.writeTempXmlFile(RuleSetString);
//            int checkResult = dtrxml.checkDTRules(ruleName);
//            WriteTA(TA_PatientInfo, "\nCheck result: "+checkResult+"\n");
//            if(checkResult == -1){
////                create a new DTRules.xml and its relative dirs
////                WriteTA(TA_PatientInfo, "Writting...\n\n"+dtrxml.createDTRules(RuleSetString) + "\nDONE...\n\n");
//                dtrxml.createDTRules(RuleSetString);
//            }
//            if(checkResult == 0){
//                //append the ruleset in the existed DTRules.xml
//                dtrxml.appendDTRules(RuleSetString);
//            }
//            if(checkResult == 1){
//                //replace the ruleset in the existed DTRules.xml
//                dtrxml.replaceDTRules(RuleSetString, ruleName);
//            }
            dtrxml.createDTRules(RuleSetString);
            //Compile the decision table
            //Set System.out PrintStream and get the compile messages
            ByteArrayOutputStream baos = new ByteArrayOutputStream(2048);
            PrintStream cacheout = new PrintStream(baos);
            PrintStream original = System.out;
            System.setOut(cacheout);
            dtrxml.Compile(dtFile);
            System.setOut(original);
            WriteTA(TA_CompileMsg, baos.toString());
            //get the decision tables from the dt xml file
            //to delete the former entry table
            Select_EntryTable.removeAllItems();
            List<String> decisiontable = dtrxml.getDecisionTables(ruleName);
            for(String str : decisiontable){
                Select_EntryTable.addItem(str);
            }
            Select_EntryTable.setSelectedIndex(0);
            Select_EntryTable.setEnabled(true);
            Compiled = true;
            Btn_RunSelectedDT.setEnabled(true);
            
        }
        catch(Exception e){
            e.printStackTrace();
            WriteTA(TA_CompileMsg, e.getMessage());
        }
    }//GEN-LAST:event_Btn_ComplieDTActionPerformed

    private void Btn_RunSelectedDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_RunSelectedDTActionPerformed
        if(patientList.size() == 0)
            return;
        try{
            EntryTable = Select_EntryTable.getItemAt(Select_EntryTable.getSelectedIndex());
            edu.dhu.DTRules.DTRulesPatientDev dtrpd = edu.dhu.DTRules.DTRulesPatientDev.getInstance();
            for(Patients pt : patientList){
                List<edu.dhu.DTRules.entities.Result> results = dtrpd.doExamine((edu.dhu.DTRules.entities.Patient)pt.ConvertToDTRulesDataType(),
                        EntryTable);
                if(results.size() != 0){
                    WriteTA(TA_Results, "\n\nResult of patient "+pt.getFullName());
                    for(edu.dhu.DTRules.entities.Result result : results){
                        WriteTA(TA_Results, "\n"+result.getResultCode()+"--->"+result.getResultMessage());
                    }
                }
            }
            Tested = true;
            CheckForUpload();
        }
        catch(Exception e){
            e.printStackTrace();
            WriteTA(TA_Results, "\n\nError occrred: " + e.getMessage());
        }
    }//GEN-LAST:event_Btn_RunSelectedDTActionPerformed

    private void Btn_UploadDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_UploadDTActionPerformed
        //to upload the runnable DTRules to the database
        //we need:
        //1.RuleSetName...done
        //2.The RuleSet, content of the part of the DTRules.xml...done
        //3.The three xml file
        //4.Entry table name...done
        try{
            DTRulesXML dtrxml = DTRulesXML.getInstance();
            String DTXMLContent = dtrxml.readDTXML();// read the tmp xml file, and the RuleSetName parameter is not used at all
            System.out.println("XML String Read done...");
            GaleDTRulesDAO gdtrdao = new GaleDTRulesDAO();
            StringBuilder Attributes = new StringBuilder();
            Attributes.append(";");
            if(CB_BMI.isSelected())
                Attributes.append("BMI;");
            if(CB_HR.isSelected())
                Attributes.append("HR;");
            if(CB_Floors.isSelected())
                Attributes.append("Floors;");
            if(CB_Sleep.isSelected())
                Attributes.append("Sleep;");
            if(CB_Steps.isSelected())
                Attributes.append("Steps;");
            if(CB_Weight.isSelected())
                Attributes.append("Weight;");
            String RuleSetName = TB_RuleSetName.getText();
            if("".equals(RuleSetName))
                WriteTA(TA_Results, "\nThe RuleSet name has not be inputed yet...");
            
            //check for the RuleName
            DefaultTableModel dt = gdtrdao.getTableModel(RuleSetName);
            int count = dt.getRowCount();
            if(count > 0){
                //has the same name of RuleName
                //should ask for overwritting
                int n=JOptionPane.showConfirmDialog(null, "Rule name "+RuleSetName+" already exists, will you overwrite it?"
                        ,"ATTENTION!",JOptionPane.YES_NO_OPTION);
                if(n == JOptionPane.OK_OPTION){
                    //up date here...
                    if(gdtrdao.updateDTRules(RuleSetName, Attributes.toString(), EntryTable, DTXMLContent))
                        JOptionPane.showConfirmDialog(null, "UpDate Done...", "Info",JOptionPane.DEFAULT_OPTION);
                    else
                        JOptionPane.showConfirmDialog(null, "UpDate Failed...", "Info",JOptionPane.DEFAULT_OPTION);
                }
                return;
            }
            
            if(gdtrdao.insertDTRules(RuleSetName, Attributes.toString(), EntryTable, DTXMLContent))
                JOptionPane.showConfirmDialog(null, "Upload Done...", "Info",JOptionPane.DEFAULT_OPTION);
            else
                JOptionPane.showConfirmDialog(null, "Upload Failed...", "Info",JOptionPane.DEFAULT_OPTION);
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_Btn_UploadDTActionPerformed

    private void CB_BMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_BMIActionPerformed
        CheckForUpload();
    }//GEN-LAST:event_CB_BMIActionPerformed

    private void CB_FloorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_FloorsActionPerformed
        CheckForUpload();
    }//GEN-LAST:event_CB_FloorsActionPerformed

    private void CB_HRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_HRActionPerformed
        CheckForUpload();
    }//GEN-LAST:event_CB_HRActionPerformed

    private void CB_SleepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_SleepActionPerformed
        CheckForUpload();
    }//GEN-LAST:event_CB_SleepActionPerformed

    private void CB_StepsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_StepsActionPerformed
        CheckForUpload();
    }//GEN-LAST:event_CB_StepsActionPerformed

    private void CB_WeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_WeightActionPerformed
        CheckForUpload();
    }//GEN-LAST:event_CB_WeightActionPerformed

    private void Btn_SelectRuleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SelectRuleNameActionPerformed
        
        dtRulesSelectRuleName dtrsName = new dtRulesSelectRuleName(this, true);
        dtrsName.setVisible(true);
        
    }//GEN-LAST:event_Btn_SelectRuleNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dtRulesTestingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dtRulesTestingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dtRulesTestingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dtRulesTestingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dtRulesTestingGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_ComplieDT;
    private javax.swing.JButton Btn_RunSelectedDT;
    private javax.swing.JButton Btn_Search;
    private javax.swing.JButton Btn_SelectDT;
    private javax.swing.JButton Btn_SelectRuleName;
    private javax.swing.JButton Btn_UploadDT;
    private javax.swing.JCheckBox CB_BMI;
    private javax.swing.JCheckBox CB_Floors;
    private javax.swing.JCheckBox CB_HR;
    private javax.swing.JCheckBox CB_Sleep;
    private javax.swing.JCheckBox CB_Steps;
    private javax.swing.JCheckBox CB_Weight;
    private javax.swing.JTextField INPT_PName;
    private javax.swing.JComboBox<String> Select_EntryTable;
    private javax.swing.JTextArea TA_CompileMsg;
    private javax.swing.JTextArea TA_PatientInfo;
    private javax.swing.JTextArea TA_Results;
    private javax.swing.JTextField TB_RuleSetName;
    private javax.swing.JTextField TF_SelectedFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables

    private void WriteTA(JTextArea Ta, String message) {
        Ta.append(message);
        Ta.setCaretPosition(Ta.getDocument().getLength());
    }

    private List<BMI_Dev> GetBMIDevFromDB(int patientID) {
        List<BMI_Dev> bmi = new ArrayList<>();
        GaleBMIDevDAO pdao = new GaleBMIDevDAO();
        DefaultTableModel dt = pdao.getTableModel(patientID);
        int rows = dt.getRowCount();
        int columns = dt.getColumnCount();
        Vector vct = dt.getDataVector();
        WriteTA(TA_PatientInfo,"\n\n\nBMI:\nData rows:"+rows+"---Data columns:"+columns);
        for(int i = 0; i < rows; i++){//for each row
            Vector data = (Vector)vct.get(i);
            BMI_Dev tmp = new BMI_Dev();
            Class clazz = tmp.getClass();
            for(int j = 0; j < columns; j++){//for each column
                WriteTA(TA_PatientInfo, "\n"+dt.getColumnName(j)+":"+data.get(j));
                try{
                    Method m = clazz.getMethod("set"+dt.getColumnName(j), Object.class);
                    m.invoke(tmp, data.get(j));
                }catch(Exception e){
                    System.out.println(e.getMessage());
                }
            }
            bmi.add(tmp);
        }
        return bmi;
    }

    private List<Floors_Dev> GetFloorsDevFromDB(int patientID) {
        List<Floors_Dev> flr = new ArrayList<>();
        GaleFloorsDevDAO pdao = new GaleFloorsDevDAO();
        DefaultTableModel dt = pdao.getTableModel(patientID);
        int rows = dt.getRowCount();
        int columns = dt.getColumnCount();
        Vector vct = dt.getDataVector();
        WriteTA(TA_PatientInfo,"\n\n\nFloors:\nData rows:"+rows+"---Data columns:"+columns);
        for(int i = 0; i < rows; i++){//for each row
            Vector data = (Vector)vct.get(i);
            Floors_Dev tmp = new Floors_Dev();
            Class clazz = tmp.getClass();
            for(int j = 0; j < columns; j++){//for each column
                WriteTA(TA_PatientInfo, "\n"+dt.getColumnName(j)+":"+data.get(j));
                try{
                    Method m = clazz.getMethod("set"+dt.getColumnName(j), Object.class);
                    m.invoke(tmp, data.get(j));
                }catch(Exception e){
                    System.out.println(e.getMessage());
                }
            }
            flr.add(tmp);
        }
        return flr;
    }

    private List<HR_Dev> GetHRDevFromDB(int patientID) {
        List<HR_Dev> hr = new ArrayList<>();
        GaleHRDevDAO pdao = new GaleHRDevDAO();
        DefaultTableModel dt = pdao.getTableModel(patientID);
        int rows = dt.getRowCount();
        int columns = dt.getColumnCount();
        Vector vct = dt.getDataVector();
        WriteTA(TA_PatientInfo,"\n\n\nHR:\nData rows:"+rows+"---Data columns:"+columns);
        for(int i = 0; i < rows; i++){//for each row
            Vector data = (Vector)vct.get(i);
            HR_Dev tmp = new HR_Dev();
            Class clazz = tmp.getClass();
            for(int j = 0; j < columns; j++){//for each column
                WriteTA(TA_PatientInfo, "\n"+dt.getColumnName(j)+":"+data.get(j));
                try{
                    Method m = clazz.getMethod("set"+dt.getColumnName(j), Object.class);
                    m.invoke(tmp, data.get(j));
                }catch(Exception e){
                    System.out.println(e.getMessage());
                }
            }
            hr.add(tmp);
        }
        return hr;
    }

    private List<Sleep_Dev> GetSleepDevFromDB(int patientID) {
        List<Sleep_Dev> slp = new ArrayList<>();
        GaleSleepDevDAO pdao = new GaleSleepDevDAO();
        DefaultTableModel dt = pdao.getTableModel(patientID);
        int rows = dt.getRowCount();
        int columns = dt.getColumnCount();
        Vector vct = dt.getDataVector();
        WriteTA(TA_PatientInfo,"\n\n\nSleep:\nData rows:"+rows+"---Data columns:"+columns);
        for(int i = 0; i < rows; i++){//for each row
            Vector data = (Vector)vct.get(i);
            Sleep_Dev tmp = new Sleep_Dev();
            Class clazz = tmp.getClass();
            for(int j = 0; j < columns; j++){//for each column
                WriteTA(TA_PatientInfo, "\n"+dt.getColumnName(j)+":"+data.get(j));
                try{
                    Method m = clazz.getMethod("set"+dt.getColumnName(j), Object.class);
                    m.invoke(tmp, data.get(j));
                }catch(Exception e){
                    System.out.println(e.getMessage());
                }
            }
            slp.add(tmp);
        }
        return slp;
    }

    private List<Steps_Dev> GetStepsDevFromDB(int patientID) {
        List<Steps_Dev> stp = new ArrayList<>();
        GaleStepsDevDAO pdao = new GaleStepsDevDAO();
        DefaultTableModel dt = pdao.getTableModel(patientID);
        int rows = dt.getRowCount();
        int columns = dt.getColumnCount();
        Vector vct = dt.getDataVector();
        WriteTA(TA_PatientInfo,"\n\n\nSteps:\nData rows:"+rows+"---Data columns:"+columns);
        for(int i = 0; i < rows; i++){//for each row
            Vector data = (Vector)vct.get(i);
            Steps_Dev tmp = new Steps_Dev();
            Class clazz = tmp.getClass();
            for(int j = 0; j < columns; j++){//for each column
                WriteTA(TA_PatientInfo, "\n"+dt.getColumnName(j)+":"+data.get(j));
                try{
                    Method m = clazz.getMethod("set"+dt.getColumnName(j), Object.class);
                    m.invoke(tmp, data.get(j));
                }catch(Exception e){
                    System.out.println(e.getMessage());
                }
            }
            stp.add(tmp);
        }
        return stp;
    }

    private List<Weight_Dev> GetWeightDevFromDB(int patientID) {
        List<Weight_Dev> wgt = new ArrayList<>();
        GaleWeightDevDAO pdao = new GaleWeightDevDAO();
        DefaultTableModel dt = pdao.getTableModel(patientID);
        int rows = dt.getRowCount();
        int columns = dt.getColumnCount();
        Vector vct = dt.getDataVector();
        WriteTA(TA_PatientInfo,"\n\n\nWeight:\nData rows:"+rows+"---Data columns:"+columns);
        for(int i = 0; i < rows; i++){//for each row
            
            Vector data = (Vector)vct.get(i);
            Weight_Dev tmp = new Weight_Dev();
            Class clazz = tmp.getClass();
            for(int j = 0; j < columns; j++){//for each column
                WriteTA(TA_PatientInfo, "\n"+dt.getColumnName(j)+":"+data.get(j));
                try{
                    Method m = clazz.getMethod("set"+dt.getColumnName(j), Object.class);
                    m.invoke(tmp, data.get(j));
                }catch(Exception e){
                    System.out.println(e.getMessage());
                }
            }
            wgt.add(tmp);
        }
        return wgt;
    }
    
    public void setRuleName(String ruleName){
        TB_RuleSetName.setText(ruleName);
    } 
    
}
