/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GaleDTRules.DAO.GaleDTRulesDAO;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;

/**
 *
 * @author HASEE
 */
public class dtRulesSelectRuleName extends javax.swing.JDialog {

    dtRulesTestingGUI dTestingGUI = null;
    
    /**
     * Creates new form dtRulesSelectRuleName
     * @param parent
     * @param modal
     */
    public dtRulesSelectRuleName(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        dTestingGUI = (dtRulesTestingGUI)parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TB_RuleName = new javax.swing.JTextField();
        Btn_Search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        List_RuleName = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        List_Tables = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        TA_Content = new javax.swing.JTextArea();
        Btn_Choose = new javax.swing.JButton();
        Btn_Cancel = new javax.swing.JButton();
        Btn_Confirm = new javax.swing.JButton();
        Btn_Delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select a Rule Name...");

        Btn_Search.setText("Search");
        Btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SearchActionPerformed(evt);
            }
        });

        List_RuleName.setEnabled(false);
        List_RuleName.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                List_RuleNameValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(List_RuleName);

        List_Tables.setEnabled(false);
        List_Tables.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                List_TablesValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(List_Tables);

        TA_Content.setColumns(20);
        TA_Content.setLineWrap(true);
        TA_Content.setRows(5);
        TA_Content.setWrapStyleWord(true);
        jScrollPane3.setViewportView(TA_Content);

        Btn_Choose.setText("Choose the selected Rule Name");
        Btn_Choose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ChooseActionPerformed(evt);
            }
        });

        Btn_Cancel.setText("Cancel");
        Btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CancelActionPerformed(evt);
            }
        });

        Btn_Confirm.setText("View");
        Btn_Confirm.setEnabled(false);
        Btn_Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ConfirmActionPerformed(evt);
            }
        });

        Btn_Delete.setText("Delete");
        Btn_Delete.setEnabled(false);
        Btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn_Choose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(Btn_Confirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn_Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TB_RuleName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_Search)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TB_RuleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_Confirm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_Delete))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Choose)
                    .addComponent(Btn_Cancel))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SearchActionPerformed
        //initial all the status
        //delete the list and set enable to false
        Btn_Confirm.setEnabled(false);
        Btn_Delete.setEnabled(false);
        List_Tables.removeAll();
        DefaultListModel<String> model1 = new DefaultListModel<>();
        List_RuleName.removeAll();
        List_RuleName.setModel(new DefaultListModel<>());
        TA_Content.setText("");
        List_RuleName.setEnabled(false);
        List_Tables.setEnabled(false);
        //select RuleName here
        String RuleName = TB_RuleName.getText();
        if(RuleName != null){
            GaleDTRulesDAO gdtrdao = new GaleDTRulesDAO();
            DefaultTableModel tmp = gdtrdao.getLikelyRuleNames(RuleName);
            if(tmp.getRowCount() < 1)
            {
                TA_Content.setText("No such Rule Name...\n");
                List_Tables.setModel(model1);
                return;
            }
            for(int i = 0; i < tmp.getRowCount(); i++){
                Vector vct = (Vector)tmp.getDataVector().get(i);
                model1.addElement((String)vct.get(0));
            }
            List_RuleName.setModel(model1);
            List_RuleName.setEnabled(true);
            Btn_Confirm.setEnabled(true);
            Btn_Delete.setEnabled(true);
        }
    }//GEN-LAST:event_Btn_SearchActionPerformed

    private void List_RuleNameValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_List_RuleNameValueChanged
           
    }//GEN-LAST:event_List_RuleNameValueChanged

    private void Btn_ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ConfirmActionPerformed
//        System.out.println("Selected:"+List_RuleName.getSelectedValue());
        try {
            if(List_RuleName.getSelectedValue() == null)
                return;
            DefaultListModel<String> modal2 = new DefaultListModel<>();
            //Select the content of the RuleName
            DefaultTableModel tmp = new GaleDTRulesDAO().getTableModel(List_RuleName.getSelectedValue());
            //to save the content as a temp file
            Vector vct = (Vector)tmp.getDataVector().get(0);
            for(int i = 0; i < tmp.getColumnCount(); i ++){
                if(tmp.getColumnName(i).equals("DTXMLContent"))
                {
                    File dtrules = new File(System.getProperty("user.dir") + "/__TMP.xml");
//                    System.out.println(System.getProperty("user.dir") + "/__TMP.xml");
                    dtrules.createNewFile();
                    FileOutputStream fos = new FileOutputStream(dtrules);
                    fos.write(((String)vct.get(i)).getBytes("utf-8"));
                    fos.close();
                }
            }
            //read the temp xml to DOM and give all the tables to select
            DocumentBuilder builder = DocumentBuilderFactory.newInstance().newDocumentBuilder();
            Document dtDocument = builder.parse(System.getProperty("user.dir") + "/__TMP.xml");
            NodeList dtTables = dtDocument.getElementsByTagName("decision_table");
            for(int i = 0; i < dtTables.getLength(); i++){
                Element dtElement = (Element)dtTables.item(i);
                modal2.addElement(dtElement.getElementsByTagName("table_name").item(0).getTextContent());
            }
            List_Tables.setModel(modal2);
            List_Tables.setEnabled(true);
        } catch (Exception e) {
            e.printStackTrace();
            TA_Content.append("\n"+e.getMessage());
        }
    }//GEN-LAST:event_Btn_ConfirmActionPerformed

    private void List_TablesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_List_TablesValueChanged
        //to get the content value of the selected table name
        try{
            File dtrules = new File(System.getProperty("user.dir") + "/__TMP.xml");
            FileInputStream fis = new FileInputStream(dtrules);
            byte[] content = new byte[fis.available()];
            fis.read(content);
            fis.close();
            String contentString = new String(content,"utf-8");
            String[] DT = contentString.split("<decision_table>");
            String[] DTS = contentString.split("</decision_table>");
            //<table_name></table_name>
            int start = 0;int end = 0;
            for(int i = 0; i < DT.length; i++)
            {
                if(DT[i].contains("<table_name>"+List_Tables.getSelectedValue()+"</table_name>"))
                {
                    start = contentString.indexOf(DT[i]);
                    break;
                }
            }
            for (int i = 0; i < DTS.length; i++) {
                if(DTS[i].contains("<table_name>"+List_Tables.getSelectedValue()+"</table_name>"))
                {
                    end = contentString.indexOf(DTS[i]) + DTS[i].length();
                    break;
                }
            }
            TA_Content.setText(contentString.substring(start, end));
            TA_Content.setCaretPosition(0);
        }catch(Exception e){
            e.printStackTrace();
            TA_Content.append("\n"+e.getMessage());
        }
        
    }//GEN-LAST:event_List_TablesValueChanged

    private void Btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CancelActionPerformed
        //delete the temp file and dispose
        File file = new File(System.getProperty("user.dir") + "/__TMP.xml");
        file.deleteOnExit();
        this.dispose();
    }//GEN-LAST:event_Btn_CancelActionPerformed

    private void Btn_ChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ChooseActionPerformed
        dTestingGUI.setRuleName(List_RuleName.getSelectedValue());
        File file = new File(System.getProperty("user.dir") + "/__TMP.xml");
        file.deleteOnExit();
        this.dispose();
    }//GEN-LAST:event_Btn_ChooseActionPerformed

    private void Btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DeleteActionPerformed
        //delete the selected RuleName
        if(List_RuleName.getSelectedValue() == null)
            return;
        String RuleName = List_RuleName.getSelectedValue();
        GaleDTRulesDAO gdtrdao = new GaleDTRulesDAO();
        int n=JOptionPane.showConfirmDialog(null, "Are you willing to delete "+RuleName+"?"
            ,"ATTENTION!",JOptionPane.YES_NO_OPTION);
        if(n == JOptionPane.OK_OPTION){
            if(gdtrdao.deleteDTRules(RuleName))
            {
                TA_Content.setText("Delete done...");
                Btn_Search.doClick();
            }
            else
               TA_Content.setText("Delete failed...");
        }
    }//GEN-LAST:event_Btn_DeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Cancel;
    private javax.swing.JButton Btn_Choose;
    private javax.swing.JButton Btn_Confirm;
    private javax.swing.JButton Btn_Delete;
    private javax.swing.JButton Btn_Search;
    private javax.swing.JList<String> List_RuleName;
    private javax.swing.JList<String> List_Tables;
    private javax.swing.JTextArea TA_Content;
    private javax.swing.JTextField TB_RuleName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
