/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Interface.PatientMeta.GeneralInformation;
import collections.History;
import java.text.ParseException;
import GaleAII.Gale;
import GaleAII.Reactive.Core;
import javax.swing.*;

/**
 *
 * @author Brian
 */
public class healthCareAIFullMDIParent extends javax.swing.JFrame {

    collections.History history;
    GeneralInformation currentPatient = new GeneralInformation();
    collections.Patient patient;
    Gale gale;
    boolean firstUse = false;

    /**
     * Creates new form healthCareAIFullMDIParent
     */
    public healthCareAIFullMDIParent() {
        initComponents();
        try {            
            populatePatient();
            populateHistory();            
            //runPatient();
            beginGale();
        } catch (RuntimeException rx){
            firstUse();
        } 
        catch (Exception e) {
            
        }

    }
    private void beginGale(){
        try {
           gale = new Gale(); 
        } catch (Exception e) {
        }
        
    }
    private void changeIconImage(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        historyMenu = new javax.swing.JMenu();
        generalMenuItem = new javax.swing.JMenuItem();
        historyFamilyMenuItem = new javax.swing.JMenuItem();
        immunizationMenuItem = new javax.swing.JMenuItem();
        occupationsMenuItem = new javax.swing.JMenuItem();
        illnessMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        startGaleMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        fileMenu.setText("File");
        jMenuBar1.add(fileMenu);

        historyMenu.setText("History");

        generalMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        generalMenuItem.setText("General");
        generalMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalMenuItemActionPerformed(evt);
            }
        });
        historyMenu.add(generalMenuItem);

        historyFamilyMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        historyFamilyMenuItem.setText("Family");
        historyFamilyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyFamilyMenuItemActionPerformed(evt);
            }
        });
        historyMenu.add(historyFamilyMenuItem);

        immunizationMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        immunizationMenuItem.setText("Immunizations");
        immunizationMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                immunizationMenuItemActionPerformed(evt);
            }
        });
        historyMenu.add(immunizationMenuItem);

        occupationsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        occupationsMenuItem.setText("Occupations");
        occupationsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occupationsMenuItemActionPerformed(evt);
            }
        });
        historyMenu.add(occupationsMenuItem);

        illnessMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        illnessMenuItem.setText("Illness");
        illnessMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                illnessMenuItemActionPerformed(evt);
            }
        });
        historyMenu.add(illnessMenuItem);

        jMenuBar1.add(historyMenu);

        jMenu1.setText("Gale");

        startGaleMenuItem.setText("Start Gale");
        startGaleMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGaleMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(startGaleMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void historyFamilyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyFamilyMenuItemActionPerformed
        GUI.History.familyFull familyFull = new GUI.History.familyFull(history);
        Helper.addInternalFrame(desktopPane, familyFull);
    }//GEN-LAST:event_historyFamilyMenuItemActionPerformed

    private void immunizationMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_immunizationMenuItemActionPerformed
        GUI.History.immunizationFull immunizatoinFull = new GUI.History.immunizationFull(history);
        Helper.addInternalFrame(desktopPane, immunizatoinFull);
    }//GEN-LAST:event_immunizationMenuItemActionPerformed

    private void occupationsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occupationsMenuItemActionPerformed
        GUI.History.OccupationalFull occupationalFull = new GUI.History.OccupationalFull(history);
        Helper.addInternalFrame(desktopPane, occupationalFull);
    }//GEN-LAST:event_occupationsMenuItemActionPerformed

    private void generalMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalMenuItemActionPerformed
        GUI.History.GeneralFull generalFull = new GUI.History.GeneralFull(history);
        Helper.addInternalFrame(desktopPane, generalFull);
    }//GEN-LAST:event_generalMenuItemActionPerformed

    private void illnessMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_illnessMenuItemActionPerformed
        GUI.History.illnessFull illnessFull = new GUI.History.illnessFull(history);
        
        Helper.addInternalFrame(desktopPane, illnessFull);
    }//GEN-LAST:event_illnessMenuItemActionPerformed

    private void startGaleMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGaleMenuItemActionPerformed
        Core coreEvent = new Core(gale.getClusterByName("Root"), gale, history);
        new Thread(coreEvent).start();
    }//GEN-LAST:event_startGaleMenuItemActionPerformed
    public final void populateHistory() {
        try {
            currentPatient = patient.getGeneralInformation();
            history = new History(currentPatient);
        } catch (Exception e) {
        }
    }

    public final void populatePatient() throws Exception {
        try {
            patient = new collections.Patient();
            if (patient.firstProgramUse()) {
                throw new RuntimeException("first use");
            }
        } catch (RuntimeException rx) {
            throw rx;
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    public final void firstUse(){
        firstUse = true;
        Helper.createDialogMessage("This is the first time using the program");
    }

    public final void runPatient() {
        patientFull newPatient = new patientFull(currentPatient);
        Helper.addInternalFrame(desktopPane, newPatient);
    }

    public History getHistory() {
        return history;
    }
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ParseException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            
        } catch (InstantiationException ex) {
            
        } catch (IllegalAccessException ex) {
            
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new healthCareAIFullMDIParent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane desktopPane;
    public javax.swing.JMenu fileMenu;
    public javax.swing.JMenuItem generalMenuItem;
    public javax.swing.JMenuItem historyFamilyMenuItem;
    public javax.swing.JMenu historyMenu;
    public javax.swing.JMenuItem illnessMenuItem;
    public javax.swing.JMenuItem immunizationMenuItem;
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem occupationsMenuItem;
    public javax.swing.JMenuItem startGaleMenuItem;
    // End of variables declaration//GEN-END:variables

}
