/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Interface.PatientMeta.GeneralInformation;
import collections.History;
import java.text.ParseException;
import GaleAII.Gale;
import GaleAII.Reactive.Core;
import GaleAII.Reactive.FamilyInterview;
import MainGUI.MasterGUI;
import javax.swing.*;

/**
 *
 * @author Brian
 */
public class healthCareAIFullMDIParent extends javax.swing.JFrame {

    collections.History history;
    GeneralInformation currentPatient = new GeneralInformation();
    collections.Patient patient;
    Gale gale;
    boolean firstUse = false;

    /**
     * Creates new form healthCareAIFullMDIParent
     */
    public healthCareAIFullMDIParent() {
        initComponents();
        try {
            populatePatient();
            populateHistory();
            //runPatient();
            beginGale();
        } catch (RuntimeException rx) {
            firstUse();
        } catch (Exception e) {

        }

    }

    private void beginGale() {
        try {
            gale = new Gale();
        } catch (Exception e) {
        }

    }

    private void changeIconImage() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        GenHistoryInterviewButton = new javax.swing.JButton();
        NutritionInterviewButton = new javax.swing.JButton();
        MentalHealthInterviewButton = new javax.swing.JButton();
        SleepInterviewButton = new javax.swing.JButton();
        ExerciseInterviewButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        NutritionalAdviceButton = new javax.swing.JButton();
        SleepAdviceButton = new javax.swing.JButton();
        ExerciseAdviceButton = new javax.swing.JButton();
        MentalHealthAdviceButton = new javax.swing.JButton();
        MedicalIssuesAdviceButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        GenMedicalHistoryButton = new javax.swing.JButton();
        VitalSignsButton = new javax.swing.JButton();
        FitbitVitalsButton = new javax.swing.JButton();
        FitbitVitalsButton1 = new javax.swing.JButton();
        showHistoryButton = new javax.swing.JButton();
        FitbitVitalsButton3 = new javax.swing.JButton();
        showHistoryButton1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        historyMenu = new javax.swing.JMenu();
        generalMenuItem = new javax.swing.JMenuItem();
        historyFamilyMenuItem = new javax.swing.JMenuItem();
        immunizationMenuItem = new javax.swing.JMenuItem();
        occupationsMenuItem = new javax.swing.JMenuItem();
        illnessMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        startGaleMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        desktopPane.setBackground(new java.awt.Color(128, 128, 128));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GALE: Intelligent Health Monitor and Advisor");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setName(""); // NOI18N
        desktopPane.add(jLabel1);
        jLabel1.setBounds(20, 30, 1240, 40);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        GenHistoryInterviewButton.setText("General History");
        GenHistoryInterviewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenHistoryInterviewButtonActionPerformed(evt);
            }
        });

        NutritionInterviewButton.setText("Nutritional Information");

        MentalHealthInterviewButton.setText("Mental Health");

        SleepInterviewButton.setText("Sleep Patterns");

        ExerciseInterviewButton.setText("Exercise");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GenHistoryInterviewButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NutritionInterviewButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MentalHealthInterviewButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SleepInterviewButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExerciseInterviewButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GenHistoryInterviewButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NutritionInterviewButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MentalHealthInterviewButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SleepInterviewButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExerciseInterviewButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        desktopPane.add(jPanel1);
        jPanel1.setBounds(240, 150, 170, 210);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Advisory Information");
        desktopPane.add(jLabel2);
        jLabel2.setBounds(910, 140, 170, 20);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        NutritionalAdviceButton.setText("Nutritional Advice");

        SleepAdviceButton.setText("Sleep Advice");

        ExerciseAdviceButton.setText("Exercise Advice");

        MentalHealthAdviceButton.setText("Mental Health Advice");

        MedicalIssuesAdviceButton.setText("Medical Issues Advice");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NutritionalAdviceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SleepAdviceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExerciseAdviceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MentalHealthAdviceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MedicalIssuesAdviceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NutritionalAdviceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SleepAdviceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExerciseAdviceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MentalHealthAdviceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MedicalIssuesAdviceButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        desktopPane.add(jPanel2);
        jPanel2.setBounds(910, 160, 229, 210);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Medical Interviews");
        desktopPane.add(jLabel3);
        jLabel3.setBounds(240, 130, 170, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Medical History");
        desktopPane.add(jLabel4);
        jLabel4.setBounds(570, 130, 170, 20);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        GenMedicalHistoryButton.setText("General Medical");
        GenMedicalHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenMedicalHistoryButtonActionPerformed(evt);
            }
        });

        VitalSignsButton.setText("Vital Signs");

        FitbitVitalsButton.setText("FitBit Vitals");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GenMedicalHistoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VitalSignsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FitbitVitalsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GenMedicalHistoryButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VitalSignsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FitbitVitalsButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        desktopPane.add(jPanel3);
        jPanel3.setBounds(570, 150, 170, 130);

        FitbitVitalsButton1.setText("Gale Transcript");
        FitbitVitalsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FitbitVitalsButton1ActionPerformed(evt);
            }
        });
        desktopPane.add(FitbitVitalsButton1);
        FitbitVitalsButton1.setBounds(590, 80, 120, 27);

        showHistoryButton.setText("Medical Access");
        showHistoryButton.setName(""); // NOI18N
        showHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMedicalAccess(evt);
            }
        });
        desktopPane.add(showHistoryButton);
        showHistoryButton.setBounds(540, 430, 230, 40);

        FitbitVitalsButton3.setText("Continuous Interactive Mode");
        FitbitVitalsButton3.setName(""); // NOI18N
        FitbitVitalsButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FitbitVitalsButton3ActionPerformed(evt);
            }
        });
        desktopPane.add(FitbitVitalsButton3);
        FitbitVitalsButton3.setBounds(540, 310, 230, 40);

        showHistoryButton1.setText("Histories");
        showHistoryButton1.setName(""); // NOI18N
        showHistoryButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showHistoryActionPerformed(evt);
            }
        });
        desktopPane.add(showHistoryButton1);
        showHistoryButton1.setBounds(540, 370, 230, 40);

        jButton1.setText("DTRules_Testing");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        desktopPane.add(jButton1);
        jButton1.setBounds(540, 500, 230, 40);

        fileMenu.setText("File");
        jMenuBar1.add(fileMenu);

        historyMenu.setText("History");

        generalMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        generalMenuItem.setText("General");
        generalMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalMenuItemActionPerformed(evt);
            }
        });
        historyMenu.add(generalMenuItem);

        historyFamilyMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        historyFamilyMenuItem.setText("Family");
        historyFamilyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyFamilyMenuItemActionPerformed(evt);
            }
        });
        historyMenu.add(historyFamilyMenuItem);

        immunizationMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        immunizationMenuItem.setText("Immunizations");
        immunizationMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                immunizationMenuItemActionPerformed(evt);
            }
        });
        historyMenu.add(immunizationMenuItem);

        occupationsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        occupationsMenuItem.setText("Occupations");
        occupationsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occupationsMenuItemActionPerformed(evt);
            }
        });
        historyMenu.add(occupationsMenuItem);

        illnessMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        illnessMenuItem.setText("Illness");
        illnessMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                illnessMenuItemActionPerformed(evt);
            }
        });
        historyMenu.add(illnessMenuItem);

        jMenuBar1.add(historyMenu);

        jMenu1.setText("Gale");

        startGaleMenuItem.setText("Start Gale");
        startGaleMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGaleMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(startGaleMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1260, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
        );

        desktopPane.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void historyFamilyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyFamilyMenuItemActionPerformed
        GUI.History.familyFull familyFull = new GUI.History.familyFull(history);
        Helper.addInternalFrame(desktopPane, familyFull);
    }//GEN-LAST:event_historyFamilyMenuItemActionPerformed

    private void immunizationMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_immunizationMenuItemActionPerformed
        GUI.History.immunizationFull immunizatoinFull = new GUI.History.immunizationFull(history);
        Helper.addInternalFrame(desktopPane, immunizatoinFull);
    }//GEN-LAST:event_immunizationMenuItemActionPerformed

    private void occupationsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occupationsMenuItemActionPerformed
        GUI.History.OccupationalFull occupationalFull = new GUI.History.OccupationalFull(history);
        Helper.addInternalFrame(desktopPane, occupationalFull);
    }//GEN-LAST:event_occupationsMenuItemActionPerformed

    private void generalMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalMenuItemActionPerformed
        GUI.History.GeneralFull generalFull = new GUI.History.GeneralFull(history);
        Helper.addInternalFrame(desktopPane, generalFull);
    }//GEN-LAST:event_generalMenuItemActionPerformed

    private void illnessMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_illnessMenuItemActionPerformed
        GUI.History.illnessFull illnessFull = new GUI.History.illnessFull(history);

        Helper.addInternalFrame(desktopPane, illnessFull);
    }//GEN-LAST:event_illnessMenuItemActionPerformed

    private void startGaleMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGaleMenuItemActionPerformed
        Core coreEvent = new Core(gale.getClusterByName("Root"), gale, history);
        /**
         * author: Fan Hu Handle the null pointer in the thread Date: 2/12/2017
         */
        Thread coreThread = new Thread(coreEvent);
        coreThread.setUncaughtExceptionHandler(new Thread.UncaughtExceptionHandler() {
            @Override
            public void uncaughtException(Thread t, Throwable e) {
                JOptionPane.showMessageDialog(null, "Please check and input again", "Wrong Input", JOptionPane.ERROR_MESSAGE);
                System.out.println("catch exception");
            }
        });
        coreThread.start();
    }//GEN-LAST:event_startGaleMenuItemActionPerformed

    private void GenHistoryInterviewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenHistoryInterviewButtonActionPerformed
        FamilyInterview familyInterview = new FamilyInterview(gale.getClusterByName("Family Interview"), gale, history);
        Thread familyInterviewThread = new Thread(familyInterview);
        familyInterviewThread.start();
    }//GEN-LAST:event_GenHistoryInterviewButtonActionPerformed

    private void GenMedicalHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenMedicalHistoryButtonActionPerformed
        GUI.History.GeneralFull generalFull = new GUI.History.GeneralFull(history);
        Helper.addInternalFrame(desktopPane, generalFull);
    }//GEN-LAST:event_GenMedicalHistoryButtonActionPerformed

    private void FitbitVitalsButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FitbitVitalsButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FitbitVitalsButton3ActionPerformed

    private void showHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHistoryActionPerformed
        HistoriesGUI hg = new HistoriesGUI();
        hg.setVisible(true);
    }//GEN-LAST:event_showHistoryActionPerformed

    private void showMedicalAccess(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMedicalAccess
        MasterGUI mg = new MasterGUI();
        mg.setVisible(true);
    }//GEN-LAST:event_showMedicalAccess

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dtRulesTestingGUI dtr = new dtRulesTestingGUI();
        dtr.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void FitbitVitalsButton1ActionPerformed(java.awt.event.ActionEvent evt) {

    }

    public final void populateHistory() {
        try {
            currentPatient = patient.getGeneralInformation();
            history = new History(currentPatient);
        } catch (Exception e) {
        }
    }

    public final void populatePatient() throws Exception {
        try {
            patient = new collections.Patient();
            if (patient.firstProgramUse()) {
                throw new RuntimeException("first use");
            }
        } catch (RuntimeException rx) {
            throw rx;
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public final void firstUse() {
        firstUse = true;
        Helper.createDialogMessage("This is the first time using the program");
    }

    public final void runPatient() {
        patientFull newPatient = new patientFull(currentPatient);
        Helper.addInternalFrame(desktopPane, newPatient);
    }

    public History getHistory() {
        return history;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ParseException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {

        } catch (InstantiationException ex) {

        } catch (IllegalAccessException ex) {

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {

        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new healthCareAIFullMDIParent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ExerciseAdviceButton;
    public javax.swing.JButton ExerciseInterviewButton;
    public javax.swing.JButton FitbitVitalsButton;
    public javax.swing.JButton FitbitVitalsButton1;
    public javax.swing.JButton FitbitVitalsButton3;
    public javax.swing.JButton GenHistoryInterviewButton;
    public javax.swing.JButton GenMedicalHistoryButton;
    public javax.swing.JButton MedicalIssuesAdviceButton;
    public javax.swing.JButton MentalHealthAdviceButton;
    public javax.swing.JButton MentalHealthInterviewButton;
    public javax.swing.JButton NutritionInterviewButton;
    public javax.swing.JButton NutritionalAdviceButton;
    public javax.swing.JButton SleepAdviceButton;
    public javax.swing.JButton SleepInterviewButton;
    public javax.swing.JButton VitalSignsButton;
    public javax.swing.JDesktopPane desktopPane;
    public javax.swing.JMenu fileMenu;
    public javax.swing.JMenuItem generalMenuItem;
    public javax.swing.JMenuItem historyFamilyMenuItem;
    public javax.swing.JMenu historyMenu;
    public javax.swing.JMenuItem illnessMenuItem;
    public javax.swing.JMenuItem immunizationMenuItem;
    public javax.swing.JButton jButton1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JMenuItem occupationsMenuItem;
    public javax.swing.JButton showHistoryButton;
    public javax.swing.JButton showHistoryButton1;
    public javax.swing.JMenuItem startGaleMenuItem;
    // End of variables declaration//GEN-END:variables

}
