/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.History;

import collections.History;
import Interface.History.General;
/**
 *
 * @author Brian
 */
public class GeneralFull extends javax.swing.JInternalFrame implements HistoryForm{
    General generalHistory;
    History history;
    /**
     * Creates new form GeneralFull
     * @param history
     */
    public GeneralFull(History history) {
        initComponents();
        this.history = history;
        generalHistory = history.getGeneralHistory();
        PopulateFields();
    }
    public final void PopulateFields(){
        alcoholTextField.setText(generalHistory.getAlcohol());
        educationTextField.setText(generalHistory.getEducation());
        maritalStatusTextfield.setText(generalHistory.getMaritalstatus());
        growthAndDevelopmentTextfield.setText(generalHistory.getGrowthanddevelopment());
        preganciesTextField.setText(generalHistory.getPregnancies());
        behavioralHistoryTextField.setText(generalHistory.getBehavioralhistory());
        travelTextField.setText(generalHistory.getTravel());
        bloodTypeTextField.setText(generalHistory.getBloodtype());
        rhTextField.setText(generalHistory.getRh());
        medialHistoryNotesTextArea.setText(generalHistory.getMedicalhistorynotes());
        numberOfChildrenTextField.setText(Integer.toString(generalHistory.getNumberofchildren()));
    }
    
    private General createGeneral() throws Exception{
        General newGeneral = new General();
        try {
            newGeneral.setAlcohol(alcoholTextField.getText());
            newGeneral.setEducation(educationTextField.getText());
            newGeneral.setMaritalstatus(maritalStatusTextfield.getText());
            newGeneral.setGrowthanddevelopment(growthAndDevelopmentTextfield.getText());
            newGeneral.setPregnancies(preganciesTextField.getText());
            newGeneral.setBehavioralhistory(behavioralHistoryTextField.getText());
            newGeneral.setTravel(travelTextField.getText());
            newGeneral.setBloodtype(bloodTypeTextField.getText());
            newGeneral.setRh(rhTextField.getText());
            newGeneral.setMedicalhistorynotes(medialHistoryNotesTextArea.getText());
            newGeneral.setNumberofchildren(Integer.parseInt(numberOfChildrenTextField.getText()));
            return newGeneral;
        } catch (Exception e) {
            throw e;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        personalInformationPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        educationTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        maritalStatusTextfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        growthAndDevelopmentTextfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        preganciesTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        behavioralHistoryTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        travelTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bloodTypeTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rhTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        medialHistoryNotesTextArea = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        numberOfChildrenTextField = new javax.swing.JTextField();
        drugsPanel = new javax.swing.JPanel();
        alcoholTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel2.setText("Education");

        educationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                educationTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Marital Status");

        jLabel4.setText("Growth and Development");

        jLabel5.setText("Pregnacies");

        jLabel6.setText("BehavioralHistory");

        jLabel7.setText("Travel");

        travelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                travelTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("Blood Type");

        bloodTypeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodTypeTextFieldActionPerformed(evt);
            }
        });

        jLabel9.setText("rh");

        rhTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rhTextFieldActionPerformed(evt);
            }
        });

        jLabel10.setText("Medical History Notes");

        medialHistoryNotesTextArea.setColumns(20);
        medialHistoryNotesTextArea.setRows(5);
        jScrollPane1.setViewportView(medialHistoryNotesTextArea);

        jLabel11.setText("Number of Children");

        javax.swing.GroupLayout personalInformationPanelLayout = new javax.swing.GroupLayout(personalInformationPanel);
        personalInformationPanel.setLayout(personalInformationPanelLayout);
        personalInformationPanelLayout.setHorizontalGroup(
            personalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalInformationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(personalInformationPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(maritalStatusTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(personalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, personalInformationPanelLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(growthAndDevelopmentTextfield))
                        .addGroup(personalInformationPanelLayout.createSequentialGroup()
                            .addGap(0, 88, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(educationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, personalInformationPanelLayout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addGroup(personalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel11))
                            .addGap(20, 20, 20)
                            .addGroup(personalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(behavioralHistoryTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(preganciesTextField)
                                .addComponent(numberOfChildrenTextField)))))
                .addGap(109, 109, 109)
                .addGroup(personalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalInformationPanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(personalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(personalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bloodTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(travelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rhTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(personalInformationPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        personalInformationPanelLayout.setVerticalGroup(
            personalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalInformationPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(personalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personalInformationPanelLayout.createSequentialGroup()
                        .addGroup(personalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(maritalStatusTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(personalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(educationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(personalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(growthAndDevelopmentTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(personalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(preganciesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(personalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(behavioralHistoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(personalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(numberOfChildrenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(personalInformationPanelLayout.createSequentialGroup()
                        .addGroup(personalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(travelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(personalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(bloodTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(personalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rhTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(personalInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Personal Information", personalInformationPanel);

        jLabel1.setText("Alcohol");

        javax.swing.GroupLayout drugsPanelLayout = new javax.swing.GroupLayout(drugsPanel);
        drugsPanel.setLayout(drugsPanelLayout);
        drugsPanelLayout.setHorizontalGroup(
            drugsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drugsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(alcoholTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(510, Short.MAX_VALUE))
        );
        drugsPanelLayout.setVerticalGroup(
            drugsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drugsPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(drugsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(alcoholTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(336, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Drugs", drugsPanel);

        updateButton.setText("Update History");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(updateButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateButton)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void educationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_educationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_educationTextFieldActionPerformed

    private void travelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_travelTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_travelTextFieldActionPerformed

    private void bloodTypeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodTypeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodTypeTextFieldActionPerformed

    private void rhTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rhTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rhTextFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        try {
            history.updateGeneralHistory(createGeneral());
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_updateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField alcoholTextField;
    public javax.swing.JTextField behavioralHistoryTextField;
    public javax.swing.JTextField bloodTypeTextField;
    public javax.swing.JPanel drugsPanel;
    public javax.swing.JTextField educationTextField;
    public javax.swing.JTextField growthAndDevelopmentTextfield;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTextField maritalStatusTextfield;
    public javax.swing.JTextArea medialHistoryNotesTextArea;
    public javax.swing.JTextField numberOfChildrenTextField;
    public javax.swing.JPanel personalInformationPanel;
    public javax.swing.JTextField preganciesTextField;
    public javax.swing.JTextField rhTextField;
    public javax.swing.JTextField travelTextField;
    public javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
